### ISSUE TITLE
Cache's way selector is very ugly

### ISSUE THREAD

**Issue by MasWag** [aqua-project/chisel-gaia#1]
In cache, number of way is actually hard coded in way selector as

```
        val nowWay = Mux(varTag === tagArray((varIndex << wayBits) +p UInt(0)),UInt (0),
          Mux (varTag === tagArray((varIndex << wayBits) + UInt(1)),UInt (1),UInt(2)))
```

This is very ugly, but I don't know how to write it well.

**Comment by nyuichi** [comment]
You can use MuxLookup for that purpose. See https://chisel.eecs.berkeley.edu/latest/chisel-tutorial.pdf for details.

あと日本語で良くないすか
